title: main
project_dir: '/home/jhhan/01_research/01_MICCAI/01_grandchellenge/han_seg/src/HanSeg_2023/experiments'
seed: 42
device: cuda:2
experiment:
  name: Anchor # Anchor, MidLine, SmallandHard #Segmentation metadata

data_loader:
  dataset: /home/jhhan/01_research/01_MICCAI/01_grandchellenge/han_seg/data/preprocessed/HaN-Seg/set_1/preprocessing_7CB7AA3181
  kfold: 1  # 1 is not use kfold validation other is use kfold validation
  augmentations: configs/augmentations.yaml
  batch_size: 1
  num_workers: 16
  patch_loader: False
  patch_shape:
  - 128
  - 128
  - 64
  resize_shape:
  - 288 # x
  - 288 # y
  - 64  # z
  sampler_type: UniformSampler 

model:
  name: Unet3D

loss:
  name: DiceCELoss

lr_scheduler:
  name: LambdaLR

optimizer:
  learning_rate: 0.001
  name: AdamW

trainer:
  reload: False
  checkpoint: ''
  do_train: True
  do_test: False
  do_inference: False
  epochs: 1000
