title: test
project_dir: '/path/project'
seed: 42

experiment:
  name: Anchor # Anchor, MidLine, SmallandHard #Segmentation metadata

data_loader:
  dataset: /data/HaN-Seg/set_1
  kfold: 1  # 1 is not use kfold validation other is use kfold validation
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  batch_size: 1
  num_workers: 0
  patch_shape:
  - 128
  - 128
  - 64
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: UniformSampler 

model:
  name: Unet3D

loss:
  name: DiceCELoss

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  reload: False
  checkpoint: ''
  do_train: True
  do_test: False
  do_inference: False
  epochs: 1000
